apiVersion: apps/v1
kind: Deployment
metadata:
  name: todayhapy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todayhapy
  template:
    metadata:
      labels:
        app: todayhapy
    spec:
      containers:
      - image: okteto.dev/todayhapy:latest
        name: todayhapy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8bf0a323-8284-47d4-aeef-c87f34bcf37e"
        - name: Vless_Path
          value: "/fgh76u4wrgjyu"
        - name: Vmess_UUID
          value: "8bf0a323-8284-47d4-aeef-c87f34bcf37e"
        - name: Vmess_Path
          value: "/fdbjui75u56ehtd"
        - name: Share_Path
          value: "/v2link"
